// ─── HOUSES ─────────────────────────────────────────────────
export const HOUSES = {
  watrat: {
    id: "watrat",
    name: "Wartaurus",
    nameEn: "Wartaurus",
    image: "/images/houses/wartaurus.webp",
    color: "#22c55e",
    colorHex: 0x22c55e,
    colorName: "Green",
    emoji: "🟢",
    memberCount: 22,
    commonWand: "ไม้มะค่ามง",
    commonWandImg: "/images/items/ไม้มะค่ามง_129_เขียว.webp",
    vipWand: "ไม้ตะเคียน",
    vipWandImg: "/images/items/ไม้ตะเคียน_220_เขียว.webp",
  },
  plodfindr: {
    id: "plodfindr",
    name: "Podfindor",
    nameEn: "Podfindor",
    image: "/images/houses/podfindor.webp",
    color: "#eab308",
    colorHex: 0xeab308,
    colorName: "Yellow",
    emoji: "🟡",
    memberCount: 39,
    commonWand: "ไม้ฉำฉา",
    commonWandImg: "/images/items/ไม้ฉำฉา_129_เหลือง.webp",
    vipWand: "ไม้โป๊ยเซียน",
    vipWandImg: "/images/items/ไม้โป้ยเซียน_220_เหลือง.webp",
  },
  anal: {
    id: "anal",
    name: "Analyze",
    nameEn: "Analyze",
    image: "/images/houses/analyze.webp",
    color: "#a855f7",
    colorHex: 0xa855f7,
    colorName: "Purple",
    emoji: "🟣",
    memberCount: 23,
    commonWand: "ไม้มะยม",
    commonWandImg: "/images/items/ไม้มะยม_129_ม่วง.webp",
    vipWand: "ไม้มะขามป้อม",
    vipWandImg: "/images/items/ไม้มะขามป้อม_220_ม่วง.webp",
  },
  slarf: {
    id: "slarf",
    name: "Sraraff",
    nameEn: "Sraraff",
    image: "/images/houses/sraraff.webp",
    color: "#ef4444",
    colorHex: 0xef4444,
    colorName: "Red",
    emoji: "🔴",
    memberCount: 32,
    commonWand: "ไม้พะยูง",
    commonWandImg: "/images/items/ไม้พะยูง_129_แดง.webp",
    vipWand: "ไม้สัก",
    vipWandImg: "/images/items/ไม้สัก_220_แดง.webp",
  },
};

export const HOUSE_LIST = Object.values(HOUSES);
