// ─── HOUSES ─────────────────────────────────────────────────
export const HOUSES = {
  watrat: {
    id: "watrat",
    name: "Wartaurus",
    nameEn: "Wartaurus",
    image: "/images/houses/wartaurus.webp",
    color: "#22c55e",
    colorHex: 0x22c55e,
    colorName: "Green",
    emoji: "🟢",
    memberCount: 57,
    commonWand: "ไม้มะค่ามง",
    commonWandImg: "/images/items/weapons/wand_makhamong_green.webp",
    vipWand: "ไม้ตะเคียน",
    vipWandImg: "/images/items/weapons/wand_takian_green.webp",
  },
  plodfindr: {
    id: "plodfindr",
    name: "Podfindor",
    nameEn: "Podfindor",
    image: "/images/houses/podfindor.webp",
    color: "#eab308",
    colorHex: 0xeab308,
    colorName: "Yellow",
    emoji: "🟡",
    memberCount: 52,
    commonWand: "ไม้ฉำฉา",
    commonWandImg: "/images/items/weapons/wand_chamcha_yellow.webp",
    vipWand: "ไม้โป๊ยเซียน",
    vipWandImg: "/images/items/weapons/wand_poysian_yellow.webp",
  },
  anal: {
    id: "anal",
    name: "Analyze",
    nameEn: "Analyze",
    image: "/images/houses/analyze.webp",
    color: "#a855f7",
    colorHex: 0xa855f7,
    colorName: "Purple",
    emoji: "🟣",
    memberCount: 48,
    commonWand: "ไม้มะยม",
    commonWandImg: "/images/items/weapons/wand_mayom_purple.webp",
    vipWand: "ไม้มะขามป้อม",
    vipWandImg: "/images/items/weapons/wand_makhampom_purple.webp",
  },
  slarf: {
    id: "slarf",
    name: "Sraraff",
    nameEn: "Sraraff",
    image: "/images/houses/sraraff.webp",
    color: "#ef4444",
    colorHex: 0xef4444,
    colorName: "Red",
    emoji: "🔴",
    memberCount: 61,
    commonWand: "ไม้พะยูง",
    commonWandImg: "/images/items/weapons/wand_phayung_red.webp",
    vipWand: "ไม้สัก",
    vipWandImg: "/images/items/weapons/wand_sak_red.webp",
  },
};

export const HOUSE_LIST = Object.values(HOUSES);
