// ─── MONSTERS (ทั้งหมดบนกระดาน) ──────────────────────────────
export const MONSTERS = [
  // Elite / Boss monsters (ปรับสเตตัสให้หนักแน่น ดาเมจมหาโหด สมศักดิ์ศรีบอส)
  { id: "grand_boss", name: "บอลเดอมอร์์", nameEn: "BallVoldemort", cell: 90, hp: 1800, dmg: 180, isBoss: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/granfinalboss.glb" },
  { id: "chicky", name: "ชิกกี้ (หมาตี้)", nameEn: "Chicky", cell: 75, hp: 320, dmg: 65, isElite: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ชิกกี้.glb" },
  { id: "tao_mono", name: "เต่าโมโน", nameEn: "Tao Mono", cell: 37, hp: 350, dmg: 70, isElite: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/mono.glb" },
  { id: "seaboon", name: "หมาซีบูน", nameEn: "Seaboon", cell: 79, hp: 300, dmg: 60, isElite: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/หมาซีบูน.glb" },
  { id: "mighty", name: "ไมตี้", nameEn: "Mighty", cell: 87, hp: 300, dmg: 60, isElite: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/maity.glb" },
  { id: "yaga", name: "ยาก้าดอง", nameEn: "Yaga", cell: 89, hp: 250, dmg: 68, isElite: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ยาก้า.glb" },
  { id: "pi_muet", name: "พี่มืด (ร่างมืด)", nameEn: "Pi Muet", cell: 57, hp: 280, dmg: 75, isElite: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/พี่มืด.glb" },
  { id: "bai_sung", name: "ใบซุง", nameEn: "Bai Sung", cell: 83, hp: 250, dmg: 62, isElite: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ไบ๋ซุ้ง.glb" },
  // Common monsters (ปรับตบหนักแน่น 14 - 18 DMG ให้ระบบ Recovery มีคุณค่าและสมดุล)
  { id: "daimon", name: "ไดมอน (หมาชาวปด)", nameEn: "Daimon", cell: 7, hp: 60, dmg: 16, image: "/images/monsters/common/daimon_monster.webp", modelPath: "/models/diamon_dog.glb" },
  { id: "jolong", name: "โจโล่ง", nameEn: "Jolong", cell: 9, hp: 40, dmg: 14, image: "/images/monsters/common/joe_long_monster.webp", modelPath: "/models/jo_long.glb" },
  {
    id: "nong_cake",
    name: "น้องเค้ก",
    nameEn: "Nong Cake",
    cell: 8,
    hp: 40,
    dmg: 14,
    image: "/images/monsters/common/nong_cake/frame_01.webp",
    modelPath: "/models/nong_cake.glb",
  },
  { id: "deadpool", name: "Deadpool แอน Wer น", nameEn: "Deadpool", cell: 6, hp: 45, dmg: 16, image: "/images/monsters/common/dead_pool_and_ww_monster.webp", modelPath: "/models/deadpool_wolverine.glb" },
  { id: "lew_2018", name: "เลว 2018", nameEn: "Lew 2018", cell: 14, hp: 45, dmg: 15, image: "/images/monsters/common/lew_2018_monster.webp", modelPath: "/models/เลว2018.glb" },
  { id: "chai_tong", name: "ชายต๊อง", nameEn: "Chai Tong", cell: 10, hp: 45, dmg: 15, image: "/images/monsters/common/chi_tong_monster.webp", modelPath: "/models/chi_tong.glb" },
  { id: "manut_fai", name: "5m", nameEn: "5m", cell: 2, hp: 40, dmg: 14, image: "/images/monsters/common/5m_man_monster.webp", modelPath: "/models/five_m.glb" },
  { id: "maew_a", name: "แมว เอ", nameEn: "Maew A", cell: 12, hp: 40, dmg: 14, image: "/images/monsters/common/a_monster.webp", modelPath: "/models/cat_a.glb" },
  { id: "dee", name: "ริวดี", nameEn: "Ryu Dee", cell: 5, hp: 45, dmg: 16, image: "/images/monsters/common/ริลดี_monster.webp", modelPath: "/models/ริลดี.glb" },
  { id: "little_b", name: "Little B", nameEn: "Little B", cell: 4, hp: 40, dmg: 14, image: "/images/monsters/common/little_b_monster.webp", modelPath: "/models/little_b.glb" },
  { id: "go_lang", name: "โกแลงเจาะ", nameEn: "Go Lang", cell: 40, hp: 70, dmg: 17, image: "/images/monsters/common/go_lang_monster.webp", modelPath: "/models/golang.glb" },
  { id: "kick_kick", name: "คิกๆ", nameEn: "Kick Kick", cell: 44, hp: 90, dmg: 18, image: "/images/monsters/common/kikkik_monster.webp", modelPath: "/models/คิกคิก.glb" },
  { id: "nu_uan", name: "หนูอ้วน", nameEn: "Nu Uan", cell: 73, hp: 50, dmg: 15, image: "/images/monsters/common/หนูอ้วน_monster.webp", modelPath: "/models/หนูอ้วน.glb" },
  { id: "mungty", name: "มังตี้", nameEn: "Mungty", cell: 77, hp: 70, dmg: 17, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/หมังตี้.glb" },
  { id: "pi_mong", name: "หมงหมง", nameEn: "Mong Mong", cell: 53, hp: 70, dmg: 17, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/หมงหมง.glb" },
  { id: "p_a_akatsuki", name: "พี่เออัครากระเทยแสงอุษา", nameEn: "Akatsuki", cell: 92, hp: 70, dmg: 17, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/p_a_กระเทยแสงอุษา.glb" },
  { id: "pi_rin", name: "พี่ริน", nameEn: "Pi Rin", cell: 58, hp: 60, dmg: 16, image: "/images/monsters/common/pi_rin_monster.webp", modelPath: "/models/พี่ริน.glb" },
  { id: "moonwalk", name: "Moonwalk", nameEn: "Moonwalk", cell: 3, hp: 40, dmg: 12, image: "/images/monsters/common/moonwalk_monster.webp", modelPath: "/models/moonwalk.glb" },
  // Hidden/secret monsters (ปรับดาเมจสะใจ 38 - 120 DMG)
  { id: "gollum", name: "The Leaping Gollum", nameEn: "Gollum", cell: 17, hp: 120, dmg: 38, isHidden: true, image: "/images/monsters/secret/oop_tong_monster.webp", modelPath: "/models/opptong_gollum.glb" },
  { id: "master_m", name: "Master moment", nameEn: "Master Moment", cell: 23, hp: 120, dmg: 38, isHidden: true, image: "/images/monsters/secret/master_moment_monster.webp", modelPath: "/models/มาสเตอร์โม้เหม็น.glb" },
  { id: "m_all_new", name: "M All New", nameEn: "M All New", cell: 24, hp: 120, dmg: 38, isHidden: true, image: "/images/monsters/secret/m-all-new.webp", modelPath: "/models/m_all_new.glb" },
  { id: "himi_ney", name: "หมีเนย", nameEn: "Butter Bear", cell: 25, hp: 50, dmg: 16, isHidden: true, image: "/images/monsters/secret/Butter_Bear.webp", modelPath: "/models/หมีเนย.glb" },
  { id: "okaruto", name: "โอคารุโตะ ร่างมืด", nameEn: "Okaruto Dark", cell: 26, hp: 420, dmg: 85, isHidden: true, image: "/images/monsters/secret/okaluto_monster.webp", modelPath: "/models/okaruto.glb" },
  { id: "unbeatable", name: "V2k", nameEn: "V2k", cell: 35, hp: 450, dmg: 120, isHidden: true, image: "/images/monsters/secret/พี่มิด_mini_boss.webp", modelPath: "/models/v2k.glb" },
  { id: "pi_mote", name: "พี่พ่อมด", nameEn: "Pi Mote", cell: 54, hp: 240, dmg: 60, isHidden: true, image: "/images/monsters/secret/พี่พ่อมด_monster.webp", modelPath: "/models/พ่อมดชอบกี้กี้.glb" },
  { id: "yam", name: "ยำยำ", nameEn: "YamYam", cell: 55, hp: 180, dmg: 45, isHidden: true, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ยำยำ.glb" },
  { id: "ma_tang", name: "หมาถัง", nameEn: "Ma Tang", cell: 70, hp: 280, dmg: 68, isHidden: true, image: "/images/monsters/secret/Ma_Tang.webp", modelPath: "/models/หมาถัง.glb" },
  { id: "som_normal", name: "สมอา (ร่างปกติ)", nameEn: "Som Normal", cell: 71, hp: 220, dmg: 50, isHidden: true, image: "/images/monsters/secret/Som_Normal.webp", modelPath: "/models/สมอา_ร่างปกติ.glb" },
  { id: "som_devil", name: "สมอา (ร่างปีศาจ)", nameEn: "Som Devil", cell: 72, hp: 450, dmg: 95, isHidden: true, image: "/images/monsters/secret/Som_Devil.webp", modelPath: "/models/สมอา_ร่างปีศาจ.glb" },
  // Additional character models
  { id: "bai_sung_original", name: "ใบซุง Original", nameEn: "Bai Sung Original", cell: 1, hp: 120, dmg: 28, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/bai_sung.glb" },
  { id: "dragon_fap", name: "Dragon Fap", nameEn: "Dragon Fap", cell: 11, hp: 260, dmg: 55, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/dragon_fap.glb" },
  { id: "gang_nam_mai_arp", name: "แก๊งน้ำไม่อาบ", nameEn: "Gang Nam Mai Arp", cell: 13, hp: 180, dmg: 38, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/gang_น้ำไม่อาบ.glb" },
  { id: "iron_tao", name: "Iron เต้", nameEn: "Iron Tao", cell: 15, hp: 300, dmg: 62, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/iron_เต้.glb" },
  { id: "maxky", name: "Maxky", nameEn: "Maxky", cell: 16, hp: 160, dmg: 34, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/maxky.glb" },
  { id: "nong_hamas", name: "Nong Hamas", nameEn: "Nong Hamas", cell: 18, hp: 140, dmg: 30, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/nong_hamas.glb" },
  { id: "pedo_luffy", name: "Pedo Luffy", nameEn: "Pedo Luffy", cell: 19, hp: 220, dmg: 48, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/pedo_ลูฟี่.glb" },
  { id: "ping_g", name: "Ping G", nameEn: "Ping G", cell: 20, hp: 150, dmg: 32, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ping_g.glb" },
  { id: "butter_bear_original", name: "Butter Bear Original", nameEn: "Butter Bear Original", cell: 21, hp: 100, dmg: 22, isHidden: true, image: "/images/monsters/secret/Butter_Bear.webp", modelPath: "/models/p_butter.glb" },
  { id: "p_dont_za", name: "P Dont Za", nameEn: "P Dont Za", cell: 22, hp: 190, dmg: 40, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/p_dont_za.glb" },
  { id: "p_kong", name: "P Kong", nameEn: "P Kong", cell: 27, hp: 240, dmg: 50, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/p_kong.glb" },
  { id: "webtood", name: "Webtood", nameEn: "Webtood", cell: 29, hp: 170, dmg: 36, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/webtood.glb" },
  { id: "wise_random_play", name: "Wise Random Play", nameEn: "Wise Random Play", cell: 30, hp: 210, dmg: 44, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/wise_random_play.glb" },
  { id: "kitti_bom", name: "กิตติบ๋อม", nameEn: "Kitti Bom", cell: 31, hp: 130, dmg: 28, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/กิตติบ๋อม.glb" },
  { id: "centipede_ev_shop", name: "กิ้งกือ EV Shop", nameEn: "Centipede EV Shop", cell: 32, hp: 200, dmg: 42, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/กิ้งกือ_ev_shop.glb" },
  { id: "suu_suu", name: "ซู่ซู่", nameEn: "Suu Suu", cell: 33, hp: 120, dmg: 26, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ซู่ซู่.glb" },
  { id: "pla_thong_rong_phong", name: "ปลาทองร้องพ่อง", nameEn: "Pla Thong Rong Phong", cell: 34, hp: 110, dmg: 24, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ปลาทองร้องพ่อง.glb" },
  { id: "pi_pak_ma", name: "พี่ปากหมา", nameEn: "Pi Pak Ma", cell: 36, hp: 230, dmg: 48, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/พี่ปากหมา.glb" },
  { id: "ma_moo", name: "มะมู๋", nameEn: "Ma Moo", cell: 38, hp: 140, dmg: 30, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/มะมู๋.glb" },
  { id: "malee_suay_mak", name: "มาลีสวยมาก", nameEn: "Malee Suay Mak", cell: 39, hp: 180, dmg: 38, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/มาลีสวยมาก.glb" },
  { id: "yossakorn", name: "ยศกร", nameEn: "Yossakorn", cell: 41, hp: 160, dmg: 34, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ยศกร.glb" },
  { id: "som_roy", name: "สมร่อย", nameEn: "Som Roy", cell: 42, hp: 220, dmg: 46, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/สมร่อย.glb" },
  { id: "sara_bass", name: "สราเบส", nameEn: "Sara Bass", cell: 43, hp: 190, dmg: 40, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/สราเบส.glb" },
  { id: "bank_leicester", name: "แบงค์เลสเตอร์", nameEn: "Bank Leicester", cell: 45, hp: 200, dmg: 42, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/แบงค์เลสเตอร์.glb" },
  { id: "saiji", name: "ไซจี้", nameEn: "Saiji", cell: 46, hp: 250, dmg: 52, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ไซจี้.glb" },
  { id: "ai_to_ai_den_khon", name: "ไอ้โต้ไอ้เดนคน", nameEn: "Ai To Ai Den Khon", cell: 47, hp: 280, dmg: 58, image: "/images/monsters/ชบ7000.webp", modelPath: "/models/ไอ้โต้ไอ้เดนคน.glb" },
  // Event monsters
  { id: "eva", name: "เทพธิดาเอวา", nameEn: "Eva", cell: 28, hp: 0, dmg: -30, isHidden: true, isHealer: true, image: "/images/monsters/events/eva.webp", modelPath: "/models/a_va.glb" },
];

// Build cell → monster lookup
export const MONSTER_MAP = MONSTERS.reduce((acc, m) => {
  acc[m.cell] = m;
  return acc;
}, {});
