// ─── HOUSE SKILLS ─────────────────────────────────────────────
export const SKILLS = {
  thunder_star: {
    id: "thunder_star",
    name: "Thunder Star",
    nameTh: "สายฟ้าทำลายล้าง",
    dmg: 50,
    target: "monster",
    targetType: "monster",
    categoryTh: "👾 มอนสเตอร์",
    cooldown: 3,
    description: "สร้างความเสียหาย 50 ดาเมจใส่ Monster",
    requiresTarget: null,
  },
  morelody: {
    id: "morelody",
    name: "Melody",
    nameTh: "บทเพลงกล่อมใจ",
    targetType: "self",
    categoryTh: "🛡️ ตัวเอง / บัฟ",
    cooldown: 3,
    description: "ขโมยสิทธิ์ทอยลูกเต๋าของบ้านถัดไปมาใช้",
    effect: "steal_turn",
    requiresTarget: null,
  },
  phoenix_force: {
    id: "phoenix_force",
    name: "Phoenix Force",
    nameTh: "พลังนกฟีนิกซ์ไฟ",
    dmg: 80,
    target: "player",
    targetType: "player",
    categoryTh: "🎯 ผู้เล่น",
    cooldown: 4,
    description: "โจมตีผู้เล่นบ้านอื่น 80 ดาเมจ จากทุกที่บนกระดาน",
    requiresTarget: "player",
  },
  stay_stupid: {
    id: "stay_stupid",
    name: "Stay Stupid",
    nameTh: "ยืนโง่ ๆ",
    targetType: "self",
    categoryTh: "🛡️ ตัวเอง / บัฟ",
    cooldown: 4,
    duration: 2,
    description: "หลบหลีกความเสียหายทุกรูปแบบ 2 เทิร์น",
    effect: "invincible",
    requiresTarget: null,
  },
  ngo_leng_ngeng_khiao: {
    id: "ngo_leng_ngeng_khiao",
    name: "งูเล็งเขี้ยว",
    nameTh: "งูเล็งเขี้ยว",
    targetType: "self",
    categoryTh: "🛡️ ตัวเอง / บัฟ",
    cooldown: 4,
    description: "เลือกล็อกผลลูกเต๋าเป็นเลข 1-6 ได้ตามใจชอบในการทอยครั้งถัดไป",
    effect: "lock_dice",
    requiresTarget: null,
  },
  god_ntr: {
    id: "god_ntr",
    name: "God NTR",
    nameTh: "จอมขโมยยา",
    targetType: "player",
    categoryTh: "🎯 ผู้เล่น",
    cooldown: 5,
    description: "สุ่มขโมยยา 1 ขวดจากผู้เล่นเป้าหมาย",
    effect: "steal_potion",
    requiresTarget: "player",
  },
  korat_chaos: {
    id: "korat_chaos",
    name: "Korat Chaos",
    nameTh: "โคราชเคอส",
    targetType: "all_players",
    categoryTh: "🌀 สลับตำแหน่งผู้เล่นทั้งหมด",
    cooldown: 4,
    description: "สลับตำแหน่งผู้เล่นทั้งหมดบนกระดานแบบสุ่ม",
    effect: "shuffle_positions",
    requiresTarget: null,
  },
  skunk_blast: {
    id: "skunk_blast",
    name: "Scab Dead",
    nameTh: "สแก๊บ แดด",
    targetType: "monster",
    categoryTh: "👾 มอนสเตอร์",
    cooldown: 2,
    description: "ขับไล่มอนสเตอร์ตรงหน้าหนีไปโดยไม่ต่อสู้ (ใช้กับ Boss ไม่ได้)",
    effect: "banish_monster",
    requiresTarget: "monster",
  },
};

export const SKILL_LIST = Object.values(SKILLS);
export const MAX_SKILLS_PER_HOUSE = 2;
export const SKILL_PRICE = 2000;
